# Generated by Django 5.1.1 on 2024-09-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.TextField(default=1234),
            preserve_default=False,
        ),
    ]
